[DEFAULT]
data#base.connection_string=postgresql://neondb_owner:npg_Tyi1uLmB3bUV@ep-billowing-bonus-axv9a7s0-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#data.geojson_path = Census2020_Tracts_COA.geojson # data just for Atlanta area
# data folder for files for state of interest
#data.geojson_path = data
tracts_path = import_insert.sql
sql.schema = schema.sql
#sql.populate = populate.sql 
sql.query = query.sql
sql.import = import_insert.sql
sql.truncate = import_truncate.sql
sql.map_clinics = map_clinics.sql
sql.map_shelters = map_shelters.sql
sql.shelters = shelters.sql
sql.clinics = clinics.sql
sql.map_center = map_center.sql
sql.query_outlier = query_outliers.sql
sql.boxplot_query = boxplot_query.sql
census_tracts = census_tracts
sql.pet_density = pet_density.sql
data.population_csv = georgia_population.csv 
sql.join_population = join_population.sql
data.petfinder_csv = petfinder_shelters.csv
sql.shelters_state = sql.shelters_state.sql 
sql.clinics_state = sql.clinics_state.sql 
sql.tracts_state = sql.tracts_state.sql
sql.outlier_state = sql.outlier_state.sql