tracts_path = import_insert.sql
sql.schema = schema.sql
#sql.populate = populate.sql 
sql.query = query.sql
sql.import = import_insert.sql
sql.truncate = import_truncate.sql
sql.map_clinics = map_clinics.sql
sql.map_shelters = map_shelters.sql
sql.shelters = shelters.sql
sql.clinics = clinics.sql
sql.map_center = map_center.sql
sql.query_outlier = query_outliers.sql
sql.boxplot_query = boxplot_query.sql
census_tracts = census_tracts
sql.pet_density = pet_density.sql
data.population_csv = georgia_population.csv 
sql.join_population = join_population.sql
data.petfinder_csv = petfinder_shelters.csv
sql.shelters_state = sql.shelters_state.sql 
sql.clinics_state = sql.clinics_state.sql 
sql.tracts_state = sql.tracts_state.sql
sql.outlier_state = sql.outlier_state.sql
sql.outlier_tract = map_outlier_tract.sql
sql.nearest_clinics = nearest_clinics.sql
style.file = style.css
fips.file = state_fips_mapping.csv