-- schema.sql
CREATE EXTENSION IF NOT EXISTS postgis; 
CREATE TABLE IF NOT EXISTS shelters ( id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, address TEXT, state_code VARCHAR(2), geom GEOMETRY(Point, 4326) ); CREATE TABLE IF NOT EXISTS clinics (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, address TEXT, geom GEOMETRY(Point, 4326)); 
CREATE TABLE IF NOT EXISTS census_tracts (id SERIAL PRIMARY KEY, tract_id VARCHAR(50) UNIQUE NOT NULL, pet_density NUMERIC, geom GEOMETRY(MultiPolygon, 4326));